version: '3.4'
services: 
    webapp:
      restart: always
      build:
        context: "./webapp/."
        dockerfile: ./Dockerfile
      ports:
        - "9050:9050"
      volumes:
        - /home/ubuntu/summary_qa/SearchSummary/webapp:/opt