version: '3.4'
services: 
    webapp:
      restart: always
      build:
        context: "./webapp/."
        dockerfile: ./Dockerfile
      ports:
        - "8501:8501"
      volumes:
        - ./webapp:/opt